# Generated by Django 2.0.1 on 2018-08-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='ended_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
