# Generated by Django 2.0.1 on 2018-08-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20180803_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='ended_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='call',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
