# Generated by Django 2.0.1 on 2018-08-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20180803_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelephoneBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount', models.DateTimeField(unique_for_month='started_at')),
                ('year', models.DateTimeField(unique_for_year='started_at')),
                ('telephone', models.IntegerField()),
            ],
        ),
    ]
