# Generated by Django 2.1 on 2018-08-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_callrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='destination',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='source',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
