# Generated by Django 2.1 on 2018-08-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20180829_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='destination',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='source',
            field=models.IntegerField(blank=True),
        ),
    ]
